//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurHak_Oto_Kiralama_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adminler()
        {
            this.Sozlesmeler = new HashSet<Sozlesmeler>();
        }
    
        public byte Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Kullaniciadi { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public string Fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesmeler> Sozlesmeler { get; set; }
    }
}
