//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurHak_Oto_Kiralama_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int Id { get; set; }
        public string Islem { get; set; }
        public Nullable<System.DateTime> Zaman { get; set; }
        public string Yetkili { get; set; }
    }
}
