//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurHak_Oto_Kiralama_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müsteriler
    {
        public int Id { get; set; }
        public string Tcno { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string EhliyetNo { get; set; }
        public string Adres { get; set; }
    }
}
