//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurHak_Oto_Kiralama_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seriler()
        {
            this.Araclar = new HashSet<Araclar>();
            this.Sozlesmeler = new HashSet<Sozlesmeler>();
        }
    
        public byte Id { get; set; }
        public Nullable<byte> Marka { get; set; }
        public string Seri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Araclar> Araclar { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesmeler> Sozlesmeler { get; set; }
    }
}
