//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurHak_Oto_Kiralama_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozlesmeler
    {
        public byte Id { get; set; }
        public string Tcno { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<byte> Aracid { get; set; }
        public string Plaka { get; set; }
        public Nullable<byte> Marka { get; set; }
        public Nullable<byte> Seri { get; set; }
        public Nullable<System.DateTime> Alistarihi { get; set; }
        public Nullable<System.DateTime> Teslimtarihi { get; set; }
        public Nullable<int> Ucret { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Adminler Adminler { get; set; }
        public virtual Araclar Araclar { get; set; }
        public virtual Markalar Markalar { get; set; }
        public virtual Seriler Seriler { get; set; }
    }
}
